behaviors:
  Robot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 30000
environment_parameters:
  max_Speed:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 0.2
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 0.3
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: Sorter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.55
        value: 0.4
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 0.5
      - name: Lesson4
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.65
        value: 0.6
      - name: Lesson5
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 0.7
      - name: Lesson6
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 0.8
      - name: Lesson7
        completion_criteria:
          measure: progress
          behavior: Robot
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0.9
      - name: Lesson8
        value: 1.0
